Create regex warning tests
ISISComputingGroup/lewis-ouroldfork pull request #3
Opened 2021-10-05 14:40 UTC by JackEAllen

## Summary of Work
Create initial unit tests for `lewis.adapters.stream.Func` in a new test file (`tests/test_stream.py`) to primarily test valid regex usage.

## Acceptance criteria
- Ensure code is readable and follows project code quality standards.
- Ensure all tests are valid and run successfully

2021-11-24 16:22 UTC, JamesKingWork requested changes, later dismissed
A couple of questions about why we are or are not testing certain return values and some requests to make the tests more readable so they can act as documentation

2021-11-24 16:22 UTC, JamesKingWork commented on tests/test_stream.py
> +from mock import MagicMock, Mock, patch
Should we not be using unittest.mock since it moved in 3.6?

2021-11-24 16:22 UTC, JamesKingWork commented on tests/test_stream.py
> +        Func(lambda x: 7, "([0-8]{1})", [int], int).can_process(b"7")
Should we not be testing the return value?

2021-11-24 16:22 UTC, JamesKingWork commented on tests/test_stream.py
> +        self.assertTrue(Func(lambda x: 5, "([0-8]{1})", [int], int).process_request(b"7"))
I may have misunderstood process_request here, but it feels like this should not return true but should return the value returned by the lambda cast to an integer?

2021-11-24 16:22 UTC, JamesKingWork commented on tests/test_stream.py
> +        self.assertTrue(Func(target_member, write_pattern, argument_mapping))
Does a constructor really return True?

2021-11-24 16:22 UTC, JamesKingWork commented on tests/test_stream.py
> +"""
Should this docstring not live in the test case?

2021-11-24 16:22 UTC, JamesKingWork commented on tests/test_stream.py
> +test additional areas of Func after adding a few tests for invalid regex triggering an error
Are these all separate sentences? Can we add some punctuation and correct capitalisation, otherwise it's quite hard to read

2021-11-24 16:22 UTC, JamesKingWork commented on tests/test_stream.py
> +            Func(lambda x: "string", "([0-8]{1})", [int], int).process_request(b"7")
I find it much easier to read a construction of Func like this: `Func(target_member, write_pattern, argument_mapping, return_mapping)` than the others e.g. `Func(lambda: 0, "[0-9]{1}", int, 1)`. It lengthens the tests but could we put things like `lambda x: 5` and `"([0-8]{1})"` into explanatory variables before using them in the constructor. Especially for this line `lambda x: "string"` could explain the test a little with a name like `function_with_string_return` or `function_that_does_not_return_an_int`.

2021-11-24 16:22 UTC, JamesKingWork commented on tests/test_stream_adapter.py
> +        self.handler = StreamHandler(MagicMock(), self.target, MagicMock)
It would be good to use explanatory fields for these MagicMocks so when someone comes to extend these tests they don't have to work out what the mocks are mocking.

2021-11-24 16:22 UTC, JamesKingWork commented on tests/test_stream_adapter.py
> +        self.assertEqual(expected, async_push.call_args[0][0])
Is there not a nice mock assert like assert_called_with we can use here? If not can we write one as a helper method of this test?

2021-11-25 11:54 UTC, JackEAllen commented on tests/test_stream.py
> +        self.assertTrue(Func(target_member, write_pattern, argument_mapping))
No, True is not returned. I used True here lazily as what is returned is just an instance of Func at a given memory address so True was simply validating that anything but an error or None was returned. I have switched this out with `assertIsInstance` of Func now.

2021-11-25 11:55 UTC, JackEAllen commented on tests/test_stream.py
> +from mock import MagicMock, Mock, patch
Have removed entirely as not actually used. Added initially under the assumption MagicMock would be needed to test Func

2021-11-25 11:56 UTC, JackEAllen commented on tests/test_stream.py
> +test additional areas of Func after adding a few tests for invalid regex triggering an error
Thanks for noticing this one, have since removed as they were simply left over comments to help me figure out how to test initially and should not be placed into production.

2021-11-25 11:59 UTC, JackEAllen commented on tests/test_stream.py
> +        self.assertTrue(Func(lambda x: 5, "([0-8]{1})", [int], int).process_request(b"7"))
Process request returns an integer so you understood correctly. I was being lazy again here using similar justification to use True as was used for `test_argument_variations_of_valid_Func_usage_without_return_mapping()`. I have since changed this to assert equals to compare against returned integer.

2021-11-25 12:07 UTC, JackEAllen commented on tests/test_stream.py
> +            Func(lambda x: "string", "([0-8]{1})", [int], int).process_request(b"7")
I have created a setup method for this and placed the occasional variable inside unitests where not re-used.
Initially chose not to use variables as I felt that this added unnecessary code which couldn't be used in parameterized. Maybe going forward, could look into swapping unnittest out for pytest to allow for using something like fixtures instead, but not really that high or a priority. 
With test naming, I'm currently of two minds about this. I agree with your point, but also want to keep test naming from being too verbose in case parameterized is used to add more edge cases later down the line to test more than just a string etc. 
I would argue that because the unit tests are so small in themselves, what is not described in the test name should easily be extracted from just reading the test itself.

2021-11-25 12:08 UTC, JackEAllen commented on tests/test_stream.py
> +        Func(lambda x: 7, "([0-8]{1})", [int], int).can_process(b"7")
Thanks, missed out actually asserting the bool returned here. Have added an assert now.

2021-11-25 14:20 UTC, JackEAllen commented on tests/test_stream_adapter.py
> +        self.assertEqual(expected, async_push.call_args[0][0])
I believe this one may have been written by Dom, but I can't actually remember. I've modified it slightly to add an assert_called_with. I've left in the previous line in case I've misunderstood your comment and will remove it your happy with the new line.

2021-11-25 14:21 UTC, JackEAllen commented on tests/test_stream_adapter.py
> +        self.handler = StreamHandler(MagicMock(), self.target, MagicMock)
I've changes this slightly to use variables if I understand your comment correctly.

2021-11-26 14:25 UTC, JamesKingWork approved these changes
Looks good!

2021-11-26 14:25 UTC, merged